name: deploy-to-eb

env:
  APP_NAME: caldeiraobot-app-v3
  ENV_APP_NAME: Caldeiraobotappv3-env
  S3_BUCKET: caldeirao-bot-bucket-sp
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${{github.run_id}}-${{github.run_number}}

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Get current instance ID and kill it.
        run: |
          instanceJson=$(aws autoscaling describe-auto-scaling-instances)
          echo $instanceJson > output.json
          sudo apt install -y jq
          instanceid=$(jq '.AutoScalingInstances[0].InstanceId" output.json)
          instanceid=$(sed -e 's/^"//' -e 's/"$//' <<< $instanceid)
          aws ec2 terminate-instances --instance-ids $instanceid

      #- name: Upload package to S3 bucket
      #  run: aws s3 cp ${{env.APP_NAME}}.zip s3://${{env.S3_BUCKET}}/

      #- name: Create new ElasticBeanstalk Application Version
      #  run: |
      #    aws elasticbeanstalk create-application-version \
      #    --application-name ${{env.APP_NAME}} \
      #    --source-bundle S3Bucket="${{env.S3_BUCKET}}",S3Key="${{env.APP_NAME}}.zip" \
      #    --version-label "ver-${{github.run_id}}-${{github.run_number}}" \
      #    --description "commit-sha-${{ github.sha }}"

      #- name: Deploy new ElasticBeanstalk Application Version
      #  run: aws elasticbeanstalk update-environment --environment-name ${{env.ENV_APP_NAME}} --version-label "ver-${{github.run_id}}-${{github.run_number}}"
