name: deploy-to-eb

env:
  APP_NAME: caldeiraobot-app-v3
  S3_BUCKET: caldeirao-bot-bucket
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_PLATFORM: Docker
  PIPELINE_ID: ${{github.run_id}}-${{github.run_number}}

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          touch .env 
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env 
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "LAVALINK_HOST=${{ secrets.LAVALINK_HOST }}" >> .env
          echo "LAVALINK_PASSWORD=${{ secrets.LAVALINK_PASSWORD }}" >> .env
          echo "LAVALINK_PORT=${{ secrets.LAVALINK_PORT }}" >> .env
          cat .env

      - name: Create ZIP deployment package
        run: zip -r ${{env.APP_NAME}}.zip . -x '*.git*'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Upload package to S3 bucket
        run: aws s3 cp ${{env.APP_NAME}}.zip s3://${{env.S3_BUCKET}}/

      - name: Create new ElasticBeanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{env.APP_NAME}} \
          --source-bundle S3Bucket="${{env.S3_BUCKET}}",S3Key="${{env.APP_NAME}}.zip" \
          --version-label "ver-${{github.run_id}}-${{github.run_number}}" \
          --description "commit-sha-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application Version
        run: aws elasticbeanstalk update-environment --environment-name Caldeiraobotappv2-env --version-label "ver-${{github.run_id}}-${{github.run_number}}"